// Generated by gencpp from file my_service/AddIntsResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H
#define MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct AddIntsResponse_
{
  typedef AddIntsResponse_<ContainerAllocator> Type;

  AddIntsResponse_()
    : usd(0.0)
    , eur(0.0)
    , gbp(0.0)
    , ugx(0.0)  {
    }
  AddIntsResponse_(const ContainerAllocator& _alloc)
    : usd(0.0)
    , eur(0.0)
    , gbp(0.0)
    , ugx(0.0)  {
  (void)_alloc;
    }



   typedef float _usd_type;
  _usd_type usd;

   typedef float _eur_type;
  _eur_type eur;

   typedef float _gbp_type;
  _gbp_type gbp;

   typedef float _ugx_type;
  _ugx_type ugx;





  typedef boost::shared_ptr< ::my_service::AddIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::AddIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddIntsResponse_

typedef ::my_service::AddIntsResponse_<std::allocator<void> > AddIntsResponse;

typedef boost::shared_ptr< ::my_service::AddIntsResponse > AddIntsResponsePtr;
typedef boost::shared_ptr< ::my_service::AddIntsResponse const> AddIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::AddIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::AddIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::AddIntsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.usd == rhs.usd &&
    lhs.eur == rhs.eur &&
    lhs.gbp == rhs.gbp &&
    lhs.ugx == rhs.ugx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::AddIntsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4d8e1c74981566ab299cbcfacfa93d2";
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4d8e1c74981566aULL;
  static const uint64_t static_value2 = 0xb299cbcfacfa93d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/AddIntsResponse";
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 usd\n"
"float32 eur\n"
"float32 gbp\n"
"float32 ugx\n"
"\n"
;
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::AddIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.usd);
      stream.next(m.eur);
      stream.next(m.gbp);
      stream.next(m.ugx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::AddIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "usd: ";
    Printer<float>::stream(s, indent + "  ", v.usd);
    s << indent << "eur: ";
    Printer<float>::stream(s, indent + "  ", v.eur);
    s << indent << "gbp: ";
    Printer<float>::stream(s, indent + "  ", v.gbp);
    s << indent << "ugx: ";
    Printer<float>::stream(s, indent + "  ", v.ugx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H
